# Generated by Django 2.1.2 on 2018-11-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='book_default.jpg', upload_to='book_pics'),
        ),
    ]
