# Generated by Django 2.1.2 on 2018-11-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLib', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='book_pics'),
        ),
    ]
