# Generated by Django 2.1.2 on 2018-11-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineLib', '0003_auto_20181107_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='book_default.jpg', upload_to='book_pics'),
        ),
    ]
